### ISSUE TITLE
The bot can't update the proxy ip

### ISSUE THREAD

**Issue by dadaoerv** [2ri4eUI/CFW-BOT#1]
hi :
thanks for the great work.
when I sent bot links like: https://raw.githubusercontent.com/ymyuuu/IPDB/main/bestproxy.txt, 
and it shows:
New proxy setting added ➡️ https://raw.githubusercontent.com/ymyuuu/IPDB/main/bestproxy.txt
Duplicated 'workertemp.txt' as 'yxip.txt' in 'users' directory.
but, 
after update the subscription, it still shows default ips, and no matter what I sent , the ips would't change.
I guess: maybe I kind of reach the limit of pythonanywhere for storage files? I'm sure there is enough space left.

by the way:
How to install the bot on debian, I run the code but can't install and run.

THX

**Comment by 2ri4eUI** [comment]
hi,
you are sending IP_API in middle of user creation , you have to set IP_API with ip subscription  button 
, this value will use later on for creating you subsciption worker. 
each user you will create use your new ip_api 
i created a tutorial for this 
https://github.com/2ri4eUI/CFW_Worker_Sub

unfortunately i don't have access to debian , i run it on ubuntu and pythonanywhere 

✌️

**Comment by dadaoerv** [comment]
thanks for reply
I'll try to fix the api
please write down the way deploy on ubuntu in readme.md
THX

**Comment by 2ri4eUI** [comment]
Are you getting any error while running on ubuntu ?
