### ISSUE TITLE
عدم باز شدن بعضی از سایتها

### ISSUE THREAD

**Issue by alizarei54** [2ri4eUI/CFW-BOT#3]
سلام، خیلی ممنون از ساخت همچین ربات خوبی، واقعا عالیه، یه مشکلی که هست اینه که بعضی از سایتها با این ورکر باز نمیشن، یه ورکر هست که همه سایتها رو با سرعت بالا میشه باز کرد ، لطفاً اگه ممکنه اونو توی ربات خودتون اجرا کنید لینکشو براتون میزارن
https://github.com/3Kmfi6HP/EDtunnel

**Comment by 2ri4eUI** [comment]
درود.  به زودی اپدیت جدیدی میدم ورکرهای مختلف قابل انتخاب باشند.  این ورکر هم که کار شده میتونه از وب سایتهای کلودفلری عبور کنه فقط باید از ای پی تمیز کلودفلر استفاده کنید برای ساخت کاربر . ای پی باشه نه دامین. و اینکه توسط کلودفلر اون ای پی فلگ نخورده باشه
بازم ممنون
