### ISSUE TITLE
The robot doesn't respond.

### ISSUE THREAD

**Issue by sukbearai** [2ri4eUI/CFW-BOT#4]
![image](https://github.com/2ri4eUI/CFW-BOT/assets/120086676/2b2953e0-9570-4bf0-a735-b5092f8efe6b)

**Comment by 2ri4eUI** [comment]
Hi the log show that you stoped the bot using ctrl+c command . The code should keep running
Just run python3 cfw.py
With out terminating it
After you run it you can close the browser and keep running in background

**Comment by sukbearai** [comment]
> Hi the log show that you stoped the bot using ctrl+c command . The code should keep running
> Just run python3 cfw.py
> With out terminating it
> After you run it you can close the browser and keep running in background

The robot's not responding. I didn't stop running cfw.py😭 What's the problem？

**Comment by sukbearai** [comment]
![image](https://github.com/2ri4eUI/CFW-BOT/assets/120086676/bbaa61c9-e477-4cbb-b6da-a9905a736236)

Nothing has changed at cloudflare works

**Comment by 2ri4eUI** [comment]
Run python3 install.py
Again
Maybe your .env is not set correctly or tokens didn't copy right
You have to atleast get some error Even if bot doesn't works

**Comment by sukbearai** [comment]
I checked my env with no errors, No errors were reported, I am referring to the lazy installation

**Comment by sukbearai** [comment]
![image](https://github.com/2ri4eUI/CFW-BOT/assets/120086676/63c0a4bf-e60b-4967-9671-bb761c49ab61)

I tried again, but the robot still didn't respond.

**Comment by sukbearai** [comment]
it worked!!! thx😊
