### ISSUE TITLE
How To Use the Bot? I am newbie

### ISSUE THREAD

**Issue by sukbearai** [2ri4eUI/CFW-BOT#5]

**Comment by 2ri4eUI** [comment]
Tell me what do you need to know so i help you with that
Its as easy as choosing a name
Sending a cloudflre ip or domain as your worker proxy
And seting subdomain.domain.com
You can use cloudflare worker domain as well
Subdomain.yourdomain.workers.dev

**Comment by sukbearai** [comment]
I would like to know how to create a user and successfully use it with Shadowrocket. I just tried and failed. My Works domain name is sukbearai.onflashdrive.app.🙏

**Comment by 2ri4eUI** [comment]
So your domain name is onflashdrive.app?
You can't use subdomain that already set in dns record 
And you don't need to add subdomain in dns record bot will create it for you
Use sth like this 
newuser.onflashdrive.app
