### ISSUE TITLE
ساب 

### ISSUE THREAD

**Issue by proxystore11** [2ri4eUI/CFW-BOT#6]
سلام وقت بخیر با تشکر از پروژا خوبتون لینک اشتراک رو توی نکوباکس و هدیفای اضافه میکنم نمیاد 
توی نکوباکس میزنه پراکسی وجود ندارد توی هدیفای هم اصلا لینک اضافه نمیشه میزنه پیکربندی ها معتبر نیستند 
و سوال بعدی اینه وقتی ipلیست خودم وارد میکنم بازم کانفیگ های قدیمی میاد با تشکر

**Comment by 2ri4eUI** [comment]
ممنونم
از v2rayng استفاده کنید
بات رو اپدیت کنید داخل پوشه پروژه برید و git pull رو ارسال کنید مشکل ست نشدن ip api حل شده.
