### ISSUE TITLE
سلام بعد از دریافت یویوآی‌دی کاربر جدید پیامی مبنی بر... ادامه

### ISSUE THREAD

**Issue by V2rayHAB** [2ri4eUI/CFW-BOT#8]
سلام و عرض ادب
![IMG_20240329_134957](https://github.com/2ri4eUI/CFW-BOT/assets/164790365/026a52ff-55af-467a-8299-de27338e6284)
پیامی مبنی بر این میاد که آپشنی وجود ندارد.
ابن چه مشکلی است و چگونه رفع میشود؟؟

**Comment by Mohammad-Mahdi-Aslani** [comment]
سلام منم همین مشکل رو دارم اگه میشه بگید باید چیکار کنم ؟

**Comment by 2ri4eUI** [comment]
اون ارور نیست . فکر میکنم متن پیام جوری که اینطور به نظرتون میرسه پروکشی کلودفلرتون رو بعد از دریافت این پیام ارسال کنید فرایند ساخت ادامه پیدا میکنه

**Comment by Mohammad-Mahdi-Aslani** [comment]
ممنون با اضافه کردن پروکسی حل شد

**Comment by V2rayHAB** [comment]
سلام دوباره خدمت شما. تمام مشکلات رفع شده. ممنون از راهنمایی هاتون. اما الان بدون مشکل کد رو توی پایتون راه میندازم تمام ریکوئرمنت رو با دقت وارد میکنم، پیام موفقیت آمیزش هم در ربات برام میاد، کانفیگ هم درست میکنم، لینک ها رو بهم میده، هم با tls هم بدونtls و هم لینک ساب رو وارد میکنم توی ویتوریng با موفقیت. اما نه کانفیگ ها وصل میشن نه ساب. ساب باموفقیت آپدیت میشه اما هیچکدوم از کانفیگ هاش متصل نمیشه. مشکل از کجا میتونه باشه؟ توی کلودفلر؟که چک کردم مشکلی نبود. دلیل متصل نشدن چیست؟ ممنون میشم راهنمایی کنید. ممنونممم🙏🏻

**Comment by 2ri4eUI** [comment]
درود . کار نکردن کانفیگ میتونه دلایل مختلفی داشته باشه ، مهمترینش اینه که پروکسی که در حین ساخت استفاده کردید به هر دلیلی از کار افتاده و باید از پروکسی دیگه ای استفاده کنید.
دلیل دیگه میتونه این باشه که دامینتون فیلتر باشه 
از دامین خود ورکرتون استفاده کنید که در سمت چپ صفحه ورکر وجود داره.

![image](https://github.com/2ri4eUI/CFW-BOT/assets/139592104/4d355d2d-dab5-436c-8e24-b90f8dd4cb5b)

 یعنی موقع ساخت به این صورت وارد کنید. برای هر کاربر سابدامین جدا بزنید .
subdomain.workerdomain.workers.dev

**Comment by V2rayHAB** [comment]
به به یعنی لذت میبرم از راهنمایی هاتون و وقتی اینقدر دقیق هستید و وقت میگذارید ❤️🙏🏻
مشکل رفع شد با استفاده از دامین خود ورکرم. حالا که رفتم دیدم دامین‌م فیلتر شده😢

امروز یه توییت از شما در ایکس دیدم و از سو استفاده اون دوستای نامحترم خیلی ناراحت شدم. اما از این خوشحال شدم که شما با یه ورژن قوی دیگه از پروژه تون پاسخ و مشت محکمی بر دهان شون زدین. همین طور ادامه بدید که ما پشت شما هستیم و ما هم پشت مون به شما گرمه که مثل مَرد دارید اتصال رایگان رو ارائه میدید💪🏻 مخصوصا به اینکه توی ورژن جدید پروژه تون بدون دامین هم میشه کانفیگ ها رو راه انداخت👌🏻

**Comment by 2ri4eUI** [comment]
درود
ممنونم از پیامتون 🙏
من که در جنگ با کسی نیستم اهل مشت و لقد و دعوا هم نیستم.
هدف فقط جنگ با GFW ! انتظار بود همراه هم باشیم که بتونیم کار رو با انرژی بیشتری جلو ببریم 
که خب مثل همیشه اثری از اتحاد نبود .
اینجور پیامها رو داخل توییتر بزارید ممنون میشم تا اینجا برای بررسی مشکلات باقی بمونه ✌️🙏
