### ISSUE TITLE
It has become exceptional.

### ISSUE THREAD

**Issue by NiREvil** [2ri4eUI/CFW-BOT#9]
یه خسته نباشید و خدا قوت بگم بهت رفیق چه سکسی شده همه چی تو آپدیت جدید
از ویکی بگیییررر تا لیست کردن پروکسیا و لینک کلادفلر و کلا همه چی، جدا لذت بردم ازش

راستی اینم خواستی اضافه کن یکی از پروکسی های خیلی خفنه، پنج شیش تا آی‌پی درست حسابی پشتش هست، سنگاپور و چین و این چیزا نیست، امریکا، لوکزامبورگ، اسپانیا، ایتالیا انکلیس و آلمان، خیلی نابه

`workers.cloudflare.cyou`

این دومی هم خوبه خیلی. یدونه انگلیس داره فقط

`ircpipproxy.duckdns.org`

**Comment by 2ri4eUI** [comment]
با حمایت خیلی جلوتر از اینا میتونه بره 🙏
